language: c++
os:
- linux
sudo: required
group: travis_lts
git:
  depth: 1000000
env:
  global:
    - secure: "sMhrmxezhnWSvS+qHmvBRW4T2uvg2hIsDBOShtzXQMBBA1PbRz0heb9HQ4glsOi2R73A+oAaB/DENphb+sFpv0ImDT03YgtHZKb/VUfB0Bqt49vW7qipyA1snkoODuAWDvUPVYl/lwxwh1NRoNhQMfnUGpUcatE5/tW4Xe2cbSYGiDpUkgytRw4ClBvm0yPYnUswXd3tQ7zPJKd+sqimrlK/XG7PmaEo7REqnu77dKMd1QxQgDZpHPsU0AfANO2rbydPcaZcI+NeRbRDGXvajg7OJ3VCTsf2HgmeualtXlxyQTTa/b0K3ClOm3SxI3RnOt9V5YyFm0AV4lEhX7c4lf5fp6hQ2lc5KAAE94JtJgFBMCdZu+c3rD0DWvC6CfIg0ns9luyTG5ItB0UUsYiah3aRQZMqGfP3lHj0D7MMGH5vldxBCr32kmGV6Qp8oV0rQcpmh+/gz57wVCJxqw/Ivojvw9vztLQR2qhbdRnZBak97G3eCMWlSVMpUcsMuwuXhszl12QnkZv7TPZI9w9gSbQaUL9+AHqMKG4bVe4bac9yX5xgL4fbZjOmxSWxvs5RPq29BgovSaIIjlXSTIMytvL5cJgo48hgLavApZ6BuBHWd1/c4xpGL/j+ciS/9gWr1tl3FIcDcZzICu6CgT5g2+KXELJrTsRkMmKkwpmNs2o="
    - apiuser=joerghall

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/root/${TRAVIS_REPO_SLUG}
  -e apipwd -e apiuser -e TRAVIS_BRANCH --rm -t jhhj/cbt-pypack-centos7:1 /bin/bash
  -c "mkdir /root/${TRAVIS_REPO_SLUG}/build && cd /root/${TRAVIS_REPO_SLUG}/build && export PATH=/opt/rh/devtoolset-6/root/usr/bin:$PATH
  && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target publish"
  ; fi
